package com.example.player_finder;

import java.util.UUID;

public class Message {
    private String messageId; // The unique ID of the message, generated by UUID
    private String senderId; // User ID of the sender
    private String receiverId; // User ID of the receiver
    private String text; // Content of the message
    private String timestamp; // When the message was sent
    private boolean isRead; // Whether the message has been read

    // Constructor generates a new messageId automatically
    public Message(String senderId, String receiverId, String text, String timestamp, boolean isRead) {
        this.messageId = UUID.randomUUID().toString(); // Generate unique messageId
        this.senderId = senderId;
        this.receiverId = receiverId;
        this.text = text;
        this.timestamp = timestamp;
        this.isRead = isRead;
    }

    // Getter and setter methods
    public String getMessageId() {
        return messageId;
    }

    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    public String getSenderId() {
        return senderId;
    }

    public void setSenderId(String senderId) {
        this.senderId = senderId;
    }

    public String getReceiverId() {
        return receiverId;
    }

    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public boolean isRead() {
        return isRead;
    }

    public void setRead(boolean isRead) {
        this.isRead = isRead;
    }
}


